routes/web.php
<?php

use App\Http\Controllers\BookController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('student', StudentController::class, ['middleware' => 'auth']);
Route::resource('book', BookController::class, ['middleware' => 'auth']);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'first_name',
        'address',
        'courses',
        'gender',
        'contact',
        'level',
        'establishment',
        'book'
    ];

}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // dd($request->all());
        $student = Student::create([
            'name' => $request->input('name'),
            'first_name' => $request->input('first_name'),
            'gender' => $request->input('gender'),
            'level' => $request->input('level'),
            'address' => $request->input('address'),
            'contact' => $request->input('contact'),
            'establishment' => $request->input('establishment'),
            'courses' => $request->input('courses'),
            'book' => $request->input('book')
        ]);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        $books = Book::orderBy('title', 'asc')->get();
        // dd($books);
        return view('student.edit', ['student' => $student, 'books' => $books]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $student->update([
            'name' => $request->input('name'),
            'first_name' => $request->input('first_name'),
            'gender' => $request->input('gender'),
            'level' => $request->input('level'),
            'address' => $request->input('address'),
            'contact' => $request->input('contact'),
            'establishment' => $request->input('establishment'),
            'courses' => $request->input('courses'),
            'book' => $request->input('book')
        ]);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        //
    }
}

app/Http/Livewire/StudentTable.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class StudentTable extends Component
{
    use WithPagination

    public function render()
    {
        return view('livewire.student-table', [
            
        ]);
    }
}

resources/views/student/edit.blade.php
<form action="{{ route('student.update', $student->id) }}" class="row g-3" method="POST">
  @csrf
  @method('put')
  <div class="col-md-6">
    <label for="name" class="form-label">Nom</label>
    <input type="text" class="form-control rounded-0 border-0 border-bottom bg-input" id="name" name="name"
      placeholder="Votre nom" value="{{ $student->name }}">
  </div>
  <div class="col-md-6">
    <label for="first_name" class="form-label">Prénom</label>
    <input type="text" class="form-control rounded-0 border-0 border-bottom bg-input" id="first_name" name="first_name"
      placeholder="Votre prénom" value="{{ $student->first_name }}">
  </div>
  <div class="col-12">
    <label for="establishment" class="form-label">Etablissement</label>
    <input type="text" class="form-control rounded-0 border-0 border-bottom bg-input" id="establishment"
      name="establishment" placeholder="Votre etablissement" value="{{ $student->establishment }}">
  </div>
  <div class="col-12">
    <label for="book" class="form-label">Livre</label>
    <select class="form-select rounded-0 border-0 border-bottom bg-input" aria-label="Default select example" id="book"
      name="book">
      <option value="">Choisir un livre</option>
      @foreach ($books as $book)
      @if ($book->title == $student->book)
      <option value="{{ $book->title }}" selected>{{ $book->title }}</option>
      @endif
      <option value="{{ $book->title }}">{{ $book->title }}</option>
      @endforeach
    </select>
  </div>
  <div class="col-md-6">
    <label for="level" class="form-label">Niveau</label>
    <input type="text" class="form-control rounded-0 border-0 border-bottom bg-input" id="level" name="level"
      placeholder="Niveau d'etude" value="{{ $student->level }}">
  </div>
  <div class="col-md-6">
    <label for="courses" class="form-label">Filière</label>
    <input type="text" class="form-control rounded-0 border-0 border-bottom bg-input" id="courses" name="courses"
      placeholder="ex: science" value="{{ $student->courses }}">
  </div>
  <div class="col-12">
    <label for="contact" class="form-label">Contact</label>
    <input type="text" class="form-control rounded-0 border-0 border-bottom bg-input" id="contact" name="contact"
      placeholder="03x xx xxx xx" value="{{ $student->contact }}">
  </div>
  <div class="col-12">
    <label for="address" class="form-label">Adresse</label>
    <input type="text" class="form-control rounded-0 border-0 border-bottom bg-input" id="address"
      placeholder="1234 Mahamasina" name="address" value="{{ $student->address }}">
  </div>
  <div class="form-check col-md-6 ms-2">
    @if ($student->gender == 'Homme')
    <input class="form-check-input" type="radio" name="gender" id="homme" value="Homme" checked>
    @else
    <input class="form-check-input" type="radio" name="gender" id="homme" value="Homme">
    @endif
    <label class="form-check-label" for="homme">
      Homme
    </label>
  </div>
  <div class="form-check col-md-6 mt-0 ms-2">
    @if ($student->gender == 'Femme')
    <input class="form-check-input" type="radio" name="gender" id="femme" value="Femme" checked>
    @else
    <input class="form-check-input" type="radio" name="gender" id="femme" value="Femme">
    @endif
    <label class="form-check-label" for="femme">
      Femme
    </label>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-secondary rounded-0">Mettre a jour</button>
  </div>
</form>